# Generated by Django 5.2.4 on 2025-07-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="max_grade",
            field=models.PositiveIntegerField(default=100, verbose_name="أقصى درجة"),
        ),
    ]
